name: Deploy Web App to GitHub Pages

on:
  push:
    branches:
      - main  
permissions:
  contents: write
  pages: write
  id-token: write
  repository-projects: write
jobs:
  preparation:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

  CI:
    runs-on: windows-latest
    needs: preparation
    steps:
      - uses: actions/checkout@v4
      - name: Admin dependencies
        run: 
          npm i ./admin
      - name: Server dependencies
        run: 
          npm i ./server
     
      - name: Web dependencies
        run: 
          npm i ./web
      - name: Build Web
        run: 
          cd web && npm run build
          
      - name: Commit build files
        run: |
          git config --global user.name "mierjia" 
          git config --global user.email "2745414799@qq.com" 
          
          # 将生成的文件添加到仓库
          git add -f web/dist   # 构建结果位于 dist 文件夹
          
          # 提交并推送到仓库
          git commit -m "Add build files"
          git push -f origin main  # 推送到 main 分支
        env:
          # 使用 GitHub Actions 自动提供的 GITHUB_TOKEN，避免手动配置 token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CD-web:
    runs-on: windows-latest
    needs: CI
    steps:
      - uses: actions/checkout@v4
      - name: Web deploy
        run: 
          cd web && npm run serve       
  CD-server:
    runs-on: windows-latest
    needs: CI
    steps:
      - uses: actions/checkout@v4
      - name: server deploy
        run: 
          cd server && npm run serve       
  Page:
    environment:
      name: github-pages
      url:  http://localhost:8080/
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: web/dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
